export bene="/mnt/c/Users/Bene"
export uni="/mnt/c/Uni"
export unis="/mnt/c/Uni/SS17"
export uniw="/mnt/c/Uni/WS1718"
export dev="/mnt/c/dev"

alias ..="cd .."
alias ...="cd ../.."
alias bene="cd /mnt/c/Users/Bene"
alias uni="cd /mnt/c/Uni"
alias unis="cd /mnt/c/Uni/SS18"
alias uniw="cd /mnt/c/Uni/WS1718"
alias dev="cd /mnt/c/dev"
alias fa="cd /mnt/c/Uni/SS17/Ferienakademie/fa2017"
alias tutor="cd /mnt/c/Uni/WS1718/Tutor-PGdP"
alias bx="unis; cd bx"

alias l="ls -alFh"
alias md="mkdir -p"
alias o="less -q"
alias gits="git status"
alias clip="wcmd clip"
alias sha384="openssl dgst -sha384 -binary | openssl enc -base64 -A"
alias untar="tar -xzf"

alias javac="wcmd javac -encoding utf-8"
alias java="wcmd java"
alias dotnet="wcmd dotnet"
